apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  jwt-secret-key: {{ required "backend.env.JWT_SECRET_KEY is required" .Values.backend.env.JWT_SECRET_KEY | default "CHANGE-ME-IN-PRODUCTION" | quote }}
  postgres-dsn: "postgresql+asyncpg://{{ .Values.postgres.auth.username }}:{{ .Values.postgres.auth.password }}@{{ .Release.Name }}-postgres:5432/{{ .Values.postgres.auth.database }}"
  {{- if .Values.backend.vault.enabled }}
  vault-token: {{ .Values.backend.vault.token | default "" | quote }}
  {{- end }}
