"""Initial baseline

Revision ID: 1fbcdc4642d4
Revises: 
Create Date: 2026-03-27 03:30:41.204798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fbcdc4642d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyst_verdicts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=True),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('analyst_id', sa.String(length=36), nullable=False),
    sa.Column('notes', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyst_verdicts_tenant_id'), 'analyst_verdicts', ['tenant_id'], unique=False)
    op.create_table('connectors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('connection_pattern', sa.String(length=16), nullable=False),
    sa.Column('config_json', sa.String(length=4096), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connectors_tenant_id'), 'connectors', ['tenant_id'], unique=False)
    op.create_table('entity_edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('source_entity', sa.String(length=128), nullable=False),
    sa.Column('target_entity', sa.String(length=128), nullable=False),
    sa.Column('relationship_type', sa.String(length=64), nullable=False),
    sa.Column('campaign_id', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entity_edges_src', 'entity_edges', ['tenant_id', 'source_entity'], unique=False)
    op.create_index(op.f('ix_entity_edges_campaign_id'), 'entity_edges', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_entity_edges_tenant_id'), 'entity_edges', ['tenant_id'], unique=False)
    op.create_table('incident_annotations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('content', sa.String(length=4096), nullable=False),
    sa.Column('annotation_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_annotations_incident_id'), 'incident_annotations', ['incident_id'], unique=False)
    op.create_table('meta_learner_weights',
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('weight_ensemble', sa.Float(), nullable=False),
    sa.Column('weight_vae', sa.Float(), nullable=False),
    sa.Column('weight_hst', sa.Float(), nullable=False),
    sa.Column('weight_temporal', sa.Float(), nullable=False),
    sa.Column('weight_adversarial', sa.Float(), nullable=False),
    sa.Column('verdicts_processed', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('paused_playbook_states',
    sa.Column('approval_id', sa.String(length=64), nullable=False),
    sa.Column('playbook_id', sa.String(length=64), nullable=False),
    sa.Column('paused_node_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('approval_id')
    )
    op.create_table('playbook_templates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('nodes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_metadata',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('report_name', sa.String(length=256), nullable=False),
    sa.Column('report_type', sa.String(length=64), nullable=False),
    sa.Column('generated_by', sa.String(length=36), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_metadata_tenant_id'), 'report_metadata', ['tenant_id'], unique=False)
    op.create_table('soar_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('playbook_id', sa.String(length=64), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soar_audit_logs_playbook_id'), 'soar_audit_logs', ['playbook_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=32), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_backup_codes', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_soar_audit_logs_playbook_id'), table_name='soar_audit_logs')
    op.drop_table('soar_audit_logs')
    op.drop_index(op.f('ix_report_metadata_tenant_id'), table_name='report_metadata')
    op.drop_table('report_metadata')
    op.drop_table('playbook_templates')
    op.drop_table('paused_playbook_states')
    op.drop_table('meta_learner_weights')
    op.drop_index(op.f('ix_incident_annotations_incident_id'), table_name='incident_annotations')
    op.drop_table('incident_annotations')
    op.drop_index(op.f('ix_entity_edges_tenant_id'), table_name='entity_edges')
    op.drop_index(op.f('ix_entity_edges_campaign_id'), table_name='entity_edges')
    op.drop_index('idx_entity_edges_src', table_name='entity_edges')
    op.drop_table('entity_edges')
    op.drop_index(op.f('ix_connectors_tenant_id'), table_name='connectors')
    op.drop_table('connectors')
    op.drop_index(op.f('ix_analyst_verdicts_tenant_id'), table_name='analyst_verdicts')
    op.drop_table('analyst_verdicts')
    # ### end Alembic commands ###
