"""Request ID correlation middleware.

Every inbound request gets a UUID4 trace ID that propagates through:
  - Response header:  ``X-Request-ID``
  - structlog context: bound via ``structlog.contextvars`` so it appears in
    every log line emitted during that request, without manual threading.
  - Error response bodies (see error_handler.py)

Starlette middleware ordering note
-----------------------------------
``app.add_middleware()`` builds a *stack* — the **last** call becomes the
**outermost** layer (first to execute on every request, last on responses).
This middleware must be added last in ``create_app()`` so the ContextVar is
populated before routes, exception handlers, or other middleware run.

Usage in error handlers / route handlers:
    from app.middleware.request_id import request_id_ctx_var
    rid = request_id_ctx_var.get()
"""
from __future__ import annotations

import uuid
from contextvars import ContextVar

import structlog
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import Response
from starlette.types import ASGIApp

# Module-level ContextVar — one value per async task (i.e., per request)
request_id_ctx_var: ContextVar[str] = ContextVar("request_id", default="")

logger = structlog.get_logger(__name__)


class RequestIDMiddleware(BaseHTTPMiddleware):
    """Attach a UUID trace ID to every request.

    Order of precedence:
      1. ``X-Request-ID`` header supplied by the client (trusted upstream proxy)
      2. Fresh UUID4 generated by this middleware
    """

    def __init__(self, app: ASGIApp, header_name: str = "X-Request-ID") -> None:
        super().__init__(app)
        self._header_name = header_name

    async def dispatch(self, request: Request, call_next) -> Response:
        # Prefer a client-supplied ID (e.g. from an upstream API gateway),
        # fall back to generating a fresh one.
        request_id = (
            request.headers.get(self._header_name)
            or str(uuid.uuid4())
        )

        # Store in ContextVar so code throughout the call stack can read it.
        token = request_id_ctx_var.set(request_id)

        # Bind to structlog's async-safe context so every log line in this
        # request automatically includes request_id without manual passing.
        structlog.contextvars.bind_contextvars(request_id=request_id)

        try:
            response = await call_next(request)
        finally:
            # Always reset — avoids leaking IDs across requests in the same
            # asyncio task if a task is reused (rare but possible with pools).
            structlog.contextvars.clear_contextvars()
            request_id_ctx_var.reset(token)

        response.headers[self._header_name] = request_id
        return response
